package main

import (
	"fmt"
	"math/big"

	// "math/rand"
	"crypto/rand"
)

func main() {
	fmt.Println("Welcome to maths in golang ")

	// var myNumberOne int = 2
	// var myNumberTwo float64 = 4.5

	// fmt.Println("The sum is: ", myNumberOne + int(myNumberTwo)) // not a valid syntax

	// RANDOM NUMBER : it si generated by two methods one bt maths and another by crypto itself

	//FOR MATHS
	// func Intn(n int) int
	// Intn returns, as an int, a non-negative pseudo-random number panics if n <= 0.

	//FOR CRYPTO
	// func Int
	// func Int(rand io.Reader, max *big.Int) (n *big.Int, err error)
	// Int returns a uniform random value in [0, max). It panics if max <= 0.

	// rand.Seed(time.Now().UnixNano())

	// fmt.Println(rand.Intn(5)+1)

	// RANDOM FROM CRYPTO
	myRandomNumber,_ := rand.Int(rand.Reader, big.NewInt(5))
	fmt.Println("The random number is: ", myRandomNumber)

}
